server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot_model?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  http:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB

##Mybatis 配置
mybatis:
  typeAliasesPackage: com.jens.springbootmodel.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/pageConfig.xml

##log日志等级配置
logging:
  level:
    root: INFO

## 监控器配置
#info:
#  contact:
#    project-name: model-service
#    author: Jens
---
server:
  port: 8090

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://mysqldb:3306/db_springboot_model?characterEncoding=utf-8&useSSL=false
    password: 123456
